### ISSUE TITLE
Margins (and a few other styles) broken when built

### ISSUE THREAD

**Issue by ggtylerr** [ggtylerr/ggtyler.dev#4]
Possibly a problem with Astro itself, need to look further into this.

Intended style (visible when using `yarn dev`)
<img src="https://github.com/ggtylerr/ggtyler.dev/assets/28498877/eb697956-8592-4334-9fc1-8cbcfddae9d1" height="500" />

Unintended style (visible when using `yarn build && yarn preview`)
<img src="https://github.com/ggtylerr/ggtyler.dev/assets/28498877/dff12aee-0541-47fa-aebd-4035378b700c" height="500" />

**Comment by king13112** [comment]
im having trouble with Instagram

Carterkenneth970@gmail.com

**Comment by ggtylerr** [comment]
?????

completely wrong place for that bud

**Comment by ggtylerr** [comment]
This has been "patched" by the above commit, [a59e4df](https://github.com/ggtylerr/ggtyler.dev/commit/a59e4df14096640c7d879da4fd202a61ccd20442), with some minor CSS tweaks done to mitigate the issue. This still isn't fixed though, notably the header links. I'm not even sure what is causing this, possibly astro-compress or astro-spa, but it's at least usable built. Running in dev mode will show added padding in some places - this is expected as it seems dev mode adds spacing.

EDIT: Astro-SPA has been removed and the issue is still present.

**Comment by ggtylerr** [comment]
Basically non existent now with the redesign
